import { HCPProfile, HCOProfile, Address, DCRProfile } from "@/types/mdm";

export const mockHCPs: HCPProfile[] = [
  {
    id: "hcp-001",
    type: "HCP",
    orgId: "ORG-12345",
    mdmId: "MDM-HCP-001",
    identifiers: ["NPI-1234567890", "DEA-AB1234567"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-15",
    firstName: "Sarah",
    lastName: "Johnson",
    npiId: "1234567890",
    speciality: ["Cardiology", "Internal Medicine"],
    organization: "Metro Health Hospital",
    address: {
      id: "addr-001",
      type: "Address",
      orgId: "ORG-12345",
      mdmId: "MDM-ADDR-001",
      identifiers: ["ADDR-001"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "123 Medical Plaza",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-0123",
    email: "sarah.johnson@metrohealth.com",
    affiliations: ["American College of Cardiology", "AMA"],
    preferredContact: "Email",
    education: [
      {
        institution: "Harvard Medical School",
        degree: "MD",
        year: "2010",
        fieldOfStudy: "Medicine",
      },
      {
        institution: "Johns Hopkins University",
        degree: "Residency",
        year: "2014",
        fieldOfStudy: "Cardiology",
      },
    ],
    license: "MA-MD-123456",
    degreeType: "MD",
  },
  {
    id: "hcp-002",
    type: "HCP",
    orgId: "ORG-12346",
    mdmId: "MDM-HCP-002",
    identifiers: ["NPI-9876543210"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-14",
    firstName: "Michael",
    lastName: "Chen",
    npiId: "9876543210",
    speciality: ["Oncology"],
    organization: "Cancer Treatment Center",
    address: {
      id: "addr-002",
      type: "Address",
      orgId: "ORG-12346",
      mdmId: "MDM-ADDR-002",
      identifiers: ["ADDR-002"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-0456",
    email: "m.chen@cancercenter.org",
    affiliations: ["ASCO", "AMA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "Stanford Medical School",
        degree: "MD",
        year: "2008",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "NY-MD-789012",
    degreeType: "MD",
  },
];

export const mockHCOs: HCOProfile[] = [
  {
    id: "hco-001",
    type: "HCO",
    orgId: "ORG-23456",
    mdmId: "MDM-HCO-001",
    identifiers: ["NPI-1122334455", "TIN-12-3456789"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-12",
    name: "Metro Health Hospital",
    npiId: "1122334455",
    organizationType: "General Hospital",
    address: {
      id: "addr-003",
      type: "Address",
      orgId: "ORG-23456",
      mdmId: "MDM-ADDR-003",
      identifiers: ["ADDR-003"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "789 Healthcare Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-1000",
    email: "info@metrohealth.com",
    affiliatedHCPs: ["hcp-001", "hcp-003", "hcp-004"],
    departments: ["Cardiology", "Oncology", "Emergency", "Surgery"],
    accreditation: ["Joint Commission", "DNV GL"],
  },
  {
    id: "hco-002",
    type: "HCO",
    orgId: "ORG-23457",
    mdmId: "MDM-HCO-002",
    identifiers: ["NPI-5566778899"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-11",
    name: "Cancer Treatment Center",
    npiId: "5566778899",
    organizationType: "Specialty Hospital",
    address: {
      id: "addr-004",
      type: "Address",
      orgId: "ORG-23457",
      mdmId: "MDM-ADDR-004",
      identifiers: ["ADDR-004"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-2000",
    email: "contact@cancercenter.org",
    affiliatedHCPs: ["hcp-002"],
    departments: ["Medical Oncology", "Radiation Oncology", "Surgical Oncology"],
    accreditation: ["ASCO QOPI", "Joint Commission"],
  },
  {
    id: "hco-003",
    type: "HCO",
    orgId: "ORG-23458",
    mdmId: "MDM-HCO-003",
    identifiers: ["NPI-7788990011", "TIN-98-7654321"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-16",
    name: "Children's Medical Center",
    npiId: "7788990011",
    organizationType: "Pediatric Hospital",
    address: {
      id: "addr-007",
      type: "Address",
      orgId: "ORG-23458",
      mdmId: "MDM-ADDR-007",
      identifiers: ["ADDR-007"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "100 Children's Way",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-213-555-3000",
    email: "info@childrensmedical.org",
    affiliatedHCPs: ["hcp-005", "hcp-006", "hcp-007"],
    departments: ["Pediatric Surgery", "Neonatal ICU", "Pediatric Cardiology", "Pediatric Oncology", "Emergency Pediatrics"],
    accreditation: ["Magnet Recognition", "Joint Commission", "Children's Hospital Association"],
  },
  {
    id: "hco-004",
    type: "HCO",
    orgId: "ORG-23459",
    mdmId: "MDM-HCO-004",
    identifiers: ["NPI-2233445566"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-17",
    name: "University Medical Research Institute",
    npiId: "2233445566",
    organizationType: "Academic Medical Center",
    address: {
      id: "addr-008",
      type: "Address",
      orgId: "ORG-23459",
      mdmId: "MDM-ADDR-008",
      identifiers: ["ADDR-008"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "500 University Circle",
      city: "Chicago",
      state: "IL",
      zipCode: "60637",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-312-555-4000",
    email: "research@umri.edu",
    affiliatedHCPs: ["hcp-001", "hcp-002", "hcp-008", "hcp-009"],
    departments: ["Clinical Research", "Neurology", "Psychiatry", "Internal Medicine", "Infectious Diseases"],
    accreditation: ["AAHRPP", "CAP", "Joint Commission"],
  },
];

export const mockAddresses: Address[] = [
  {
    id: "addr-005",
    type: "Address",
    orgId: "ORG-34567",
    mdmId: "MDM-ADDR-005",
    identifiers: ["ADDR-005"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-13",
    street: "321 Research Parkway",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-006",
    type: "Address",
    orgId: "ORG-34568",
    mdmId: "MDM-ADDR-006",
    identifiers: ["ADDR-006"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-14",
    street: "555 Medical Center Way",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
];

export const mockDCRs: DCRProfile[] = [
  {
    id: "dcr-001",
    type: "DCR",
    orgId: "ORG-45678",
    mdmId: "MDM-DCR-001",
    identifiers: ["DCR-2024-001"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-15",
    callDate: "2024-01-15",
    hcpName: "Dr. Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 45,
    callType: "In-Person",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus"],
    samplesProvided: ["CardioMed Pro - 30 samples"],
    nextFollowUp: "2024-02-15",
    notes: "Discussed latest clinical trial results. Dr. Johnson expressed interest in CardioMed Pro for high-risk patients. She mentioned that 15-20% of her patient base could benefit from this treatment. Requested peer-reviewed studies and patient case studies for review.",
  },
  {
    id: "dcr-002",
    type: "DCR",
    orgId: "ORG-45679",
    mdmId: "MDM-DCR-002",
    identifiers: ["DCR-2024-002"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-14",
    callDate: "2024-01-14",
    hcpName: "Dr. Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Emily Davis",
    callDuration: 30,
    callType: "Virtual",
    productsDiscussed: ["OncoTherapy X", "ImmuneBoost"],
    samplesProvided: [],
    nextFollowUp: "2024-02-01",
    notes: "Virtual meeting to discuss OncoTherapy X efficacy data. Dr. Chen requested additional research materials and access to the latest clinical trial publications. He is currently treating 40+ patients who could potentially benefit.",
  },
  {
    id: "dcr-003",
    type: "DCR",
    orgId: "ORG-45680",
    mdmId: "MDM-DCR-003",
    identifiers: ["DCR-2024-003"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-16",
    callDate: "2024-01-16",
    hcpName: "Dr. Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 60,
    callType: "Group Presentation",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus", "VascularCare Elite"],
    samplesProvided: ["HeartGuard Plus - 50 samples", "VascularCare Elite - 25 samples"],
    nextFollowUp: "2024-03-01",
    notes: "Group presentation to cardiology department. 8 physicians attended. Presented updated safety profile and real-world evidence data. Department head Dr. Johnson very receptive. Several physicians requested formulary addition consideration. Strong interest in combination therapy protocols.",
  },
  {
    id: "dcr-004",
    type: "DCR",
    orgId: "ORG-45681",
    mdmId: "MDM-DCR-004",
    identifiers: ["DCR-2024-004"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-17",
    callDate: "2024-01-17",
    hcpName: "Dr. Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Sarah Martinez",
    callDuration: 40,
    callType: "In-Person",
    productsDiscussed: ["OncoTherapy X", "NeoGenesis"],
    samplesProvided: ["OncoTherapy X - starter pack"],
    nextFollowUp: "2024-02-10",
    notes: "Follow-up on previous virtual call. Dr. Chen reviewed clinical data and is ready to initiate first patients on OncoTherapy X. Discussed patient selection criteria and monitoring protocols. Requested support for patient financial assistance program enrollment.",
  },
  {
    id: "dcr-005",
    type: "DCR",
    orgId: "ORG-45682",
    mdmId: "MDM-DCR-005",
    identifiers: ["DCR-2024-005"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-18",
    callDate: "2024-01-18",
    hcpName: "Dr. Rebecca Williams",
    hcoName: "Children's Medical Center",
    representativeName: "Michael Thompson",
    callDuration: 35,
    callType: "Virtual",
    productsDiscussed: ["PediaCare Advanced", "GrowthSupport Pro"],
    samplesProvided: [],
    nextFollowUp: "2024-02-20",
    notes: "Initial contact with pediatric endocrinology specialist. Dr. Williams expressed strong interest in new formulation suitable for pediatric patients. Discussed dosing considerations and safety profile in children. She is treating 60+ patients who could benefit. Requested pediatric clinical trial data and dosing calculator.",
  },
  {
    id: "dcr-006",
    type: "DCR",
    orgId: "ORG-45683",
    mdmId: "MDM-DCR-006",
    identifiers: ["DCR-2024-006"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-19",
    callDate: "2024-01-19",
    hcpName: "Dr. James Anderson",
    hcoName: "University Medical Research Institute",
    representativeName: "Emily Davis",
    callDuration: 75,
    callType: "In-Person",
    productsDiscussed: ["NeuroGen Plus", "CogniCare Advanced", "MindBalance"],
    samplesProvided: ["NeuroGen Plus - clinical evaluation pack"],
    nextFollowUp: "2024-02-25",
    notes: "Comprehensive meeting with neurology research team. Dr. Anderson and 3 colleagues attended. Discussed ongoing research collaboration opportunities and investigator-initiated trial possibilities. Strong interest in NeuroGen Plus for early-stage dementia patients. They are conducting a comparative effectiveness study and requested to include our product. Also discussed speaker bureau participation.",
  },
];

export const getAllEntities = () => {
  return [
    ...mockHCPs,
    ...mockHCOs,
    ...mockAddresses,
    ...mockDCRs,
  ];
};
