import { HCPProfile, HCOProfile, Address, DCRProfile } from "@/types/mdm";

export const mockHCPs: HCPProfile[] = [
  {
    id: "hcp-001",
    type: "HCP",
    orgId: "ORG-12345",
    mdmId: "MDM-HCP-001",
    identifiers: ["NPI-1234567890", "DEA-AB1234567"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-15",
    firstName: "Sarah",
    lastName: "Johnson",
    npiId: "1234567890",
    speciality: ["Cardiology", "Internal Medicine"],
    organization: "Metro Health Hospital",
    address: {
      id: "addr-001",
      type: "Address",
      orgId: "ORG-12345",
      mdmId: "MDM-ADDR-001",
      identifiers: ["ADDR-001"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "123 Medical Plaza",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-0123",
    email: "sarah.johnson@metrohealth.com",
    affiliations: ["American College of Cardiology", "AMA"],
    preferredContact: "Email",
    education: [
      {
        institution: "Harvard Medical School",
        degree: "MD",
        year: "2010",
        fieldOfStudy: "Medicine",
      },
      {
        institution: "Johns Hopkins University",
        degree: "Residency",
        year: "2014",
        fieldOfStudy: "Cardiology",
      },
    ],
    license: "MA-MD-123456",
    degreeType: "MD",
  },
  {
    id: "hcp-002",
    type: "HCP",
    orgId: "ORG-12346",
    mdmId: "MDM-HCP-002",
    identifiers: ["NPI-9876543210"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-14",
    firstName: "Michael",
    lastName: "Chen",
    npiId: "9876543210",
    speciality: ["Oncology"],
    organization: "Cancer Treatment Center",
    address: {
      id: "addr-002",
      type: "Address",
      orgId: "ORG-12346",
      mdmId: "MDM-ADDR-002",
      identifiers: ["ADDR-002"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-0456",
    email: "m.chen@cancercenter.org",
    affiliations: ["ASCO", "AMA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "Stanford Medical School",
        degree: "MD",
        year: "2008",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "NY-MD-789012",
    degreeType: "MD",
  },
];

export const mockHCOs: HCOProfile[] = [
  {
    id: "hco-001",
    type: "HCO",
    orgId: "ORG-23456",
    mdmId: "MDM-HCO-001",
    identifiers: ["NPI-1122334455", "TIN-12-3456789", "CLIA-12D0123456"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-12",
    name: "Metro Health Hospital",
    npiId: "1122334455",
    organizationType: "General Hospital",
    address: {
      id: "addr-003",
      type: "Address",
      orgId: "ORG-23456",
      mdmId: "MDM-ADDR-003",
      identifiers: ["ADDR-003"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "789 Healthcare Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-1000",
    email: "info@metrohealth.com",
    affiliatedHCPs: ["hcp-001", "hcp-003", "hcp-004"],
    departments: ["Cardiology", "Oncology", "Emergency Medicine", "Surgery", "Pediatrics", "Radiology"],
    accreditation: ["Joint Commission - Gold Seal", "DNV GL Healthcare", "Magnet Recognition Program"],
  },
  {
    id: "hco-002",
    type: "HCO",
    orgId: "ORG-23457",
    mdmId: "MDM-HCO-002",
    identifiers: ["NPI-5566778899", "TIN-45-9876543"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-11",
    name: "Cancer Treatment Center",
    npiId: "5566778899",
    organizationType: "Specialty Hospital",
    address: {
      id: "addr-004",
      type: "Address",
      orgId: "ORG-23457",
      mdmId: "MDM-ADDR-004",
      identifiers: ["ADDR-004"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-2000",
    email: "contact@cancercenter.org",
    affiliatedHCPs: ["hcp-002"],
    departments: ["Medical Oncology", "Radiation Oncology", "Surgical Oncology", "Hematology", "Palliative Care"],
    accreditation: ["ASCO QOPI Certification", "Joint Commission", "Commission on Cancer Accreditation"],
  },
  {
    id: "hco-003",
    type: "HCO",
    orgId: "ORG-23458",
    mdmId: "MDM-HCO-003",
    identifiers: ["NPI-7788990011", "TIN-98-7654321", "CLIA-05D0987654"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-16",
    name: "Children's Medical Center",
    npiId: "7788990011",
    organizationType: "Pediatric Hospital",
    address: {
      id: "addr-007",
      type: "Address",
      orgId: "ORG-23458",
      mdmId: "MDM-ADDR-007",
      identifiers: ["ADDR-007"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "100 Children's Way",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-213-555-3000",
    email: "info@childrensmedical.org",
    affiliatedHCPs: ["hcp-005", "hcp-006", "hcp-007"],
    departments: ["Pediatric Surgery", "Neonatal ICU", "Pediatric Cardiology", "Pediatric Oncology", "Emergency Pediatrics", "Pediatric Neurology"],
    accreditation: ["Magnet Recognition Program", "Joint Commission - Gold Seal", "Children's Hospital Association Member", "Beacon Award Excellence"],
  },
  {
    id: "hco-004",
    type: "HCO",
    orgId: "ORG-23459",
    mdmId: "MDM-HCO-004",
    identifiers: ["NPI-2233445566", "TIN-36-5432198", "CLIA-14D1122334"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-17",
    name: "University Medical Research Institute",
    npiId: "2233445566",
    organizationType: "Academic Medical Center",
    address: {
      id: "addr-008",
      type: "Address",
      orgId: "ORG-23459",
      mdmId: "MDM-ADDR-008",
      identifiers: ["ADDR-008"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "500 University Circle",
      city: "Chicago",
      state: "IL",
      zipCode: "60637",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-312-555-4000",
    email: "research@umri.edu",
    affiliatedHCPs: ["hcp-001", "hcp-002", "hcp-008", "hcp-009"],
    departments: ["Clinical Research", "Neurology", "Psychiatry", "Internal Medicine", "Infectious Diseases", "Genomics", "Immunology"],
    accreditation: ["AAHRPP Accreditation", "CAP Laboratory Accreditation", "Joint Commission", "NCQA Patient-Centered Specialty Practice"],
  },
];

export const mockAddresses: Address[] = [
  {
    id: "addr-005",
    type: "Address",
    orgId: "ORG-34567",
    mdmId: "MDM-ADDR-005",
    identifiers: ["ADDR-005"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-13",
    street: "321 Research Parkway",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-006",
    type: "Address",
    orgId: "ORG-34568",
    mdmId: "MDM-ADDR-006",
    identifiers: ["ADDR-006"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-14",
    street: "555 Medical Center Way",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
];

export const mockDCRs: DCRProfile[] = [
  {
    id: "dcr-001",
    type: "DCR",
    orgId: "ORG-45678",
    mdmId: "MDM-DCR-001",
    identifiers: ["DCR-2024-001", "VEEVA-DCR-001"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-15",
    callDate: "2024-01-15",
    hcpName: "Dr. Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 45,
    callType: "In-Person",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus"],
    samplesProvided: ["CardioMed Pro - 30 samples"],
    nextFollowUp: "2024-02-15",
    notes: "Discussed latest clinical trial results showing 23% reduction in cardiovascular events. Dr. Johnson expressed strong interest in CardioMed Pro for high-risk patients with diabetes and hypertension comorbidities. She mentioned that 15-20% of her patient base (approximately 200 patients) could benefit from this treatment. Requested peer-reviewed studies from NEJM and JAMA, patient case studies for review, and formulary addition process information. Discussed reimbursement pathways and patient assistance programs. Dr. Johnson agreed to pilot program with 10 selected patients.",
  },
  {
    id: "dcr-002",
    type: "DCR",
    orgId: "ORG-45679",
    mdmId: "MDM-DCR-002",
    identifiers: ["DCR-2024-002", "VEEVA-DCR-002"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-14",
    callDate: "2024-01-14",
    hcpName: "Dr. Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Emily Davis",
    callDuration: 30,
    callType: "Virtual",
    productsDiscussed: ["OncoTherapy X", "ImmuneBoost"],
    samplesProvided: [],
    nextFollowUp: "2024-02-01",
    notes: "Virtual meeting via Zoom to discuss OncoTherapy X Phase III efficacy data showing 35% improvement in progression-free survival. Dr. Chen requested additional research materials including mechanism of action videos, access to the latest clinical trial publications from Lancet Oncology, and detailed adverse event profiles. He is currently treating 40+ patients with metastatic disease who could potentially benefit. Discussed combination therapy protocols with existing treatments and patient monitoring requirements. Scheduled follow-up for detailed adverse event management training.",
  },
  {
    id: "dcr-003",
    type: "DCR",
    orgId: "ORG-45680",
    mdmId: "MDM-DCR-003",
    identifiers: ["DCR-2024-003", "VEEVA-DCR-003"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-16",
    callDate: "2024-01-16",
    hcpName: "Dr. Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 60,
    callType: "Group Presentation",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus", "VascularCare Elite"],
    samplesProvided: ["HeartGuard Plus - 50 samples", "VascularCare Elite - 25 samples"],
    nextFollowUp: "2024-03-01",
    notes: "Group presentation to cardiology department grand rounds. 8 physicians attended including Dr. Johnson (Department Head), Dr. Martinez (Interventional Cardiology), Dr. Patel (Heart Failure), and 5 attending cardiologists. Presented updated safety profile with 2-year real-world evidence data from 15,000+ patients and comparative effectiveness analysis vs. standard of care. Department head Dr. Johnson very receptive and supportive. Several physicians requested P&T committee formulary addition consideration for March meeting. Strong interest in combination therapy protocols for complex patients. Discussed department-wide educational program and continuing medical education opportunities. Follow-up scheduled for detailed P&T submission support.",
  },
  {
    id: "dcr-004",
    type: "DCR",
    orgId: "ORG-45681",
    mdmId: "MDM-DCR-004",
    identifiers: ["DCR-2024-004", "SFDC-DCR-004"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-17",
    callDate: "2024-01-17",
    hcpName: "Dr. Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Sarah Martinez",
    callDuration: 40,
    callType: "In-Person",
    productsDiscussed: ["OncoTherapy X", "NeoGenesis"],
    samplesProvided: ["OncoTherapy X - starter pack"],
    nextFollowUp: "2024-02-10",
    notes: "Follow-up on previous virtual call. Dr. Chen reviewed clinical data packages and is ready to initiate first 5 patients on OncoTherapy X within 2 weeks. Discussed detailed patient selection criteria: Stage III/IV disease, ECOG 0-1, adequate organ function. Reviewed monitoring protocols including baseline and week 4, 8, 12 assessments. Provided patient education materials in English and Spanish. Discussed financial assistance - requested support for patient financial assistance program enrollment and prior authorization process. Dr. Chen committed to presenting at upcoming tumor board and will facilitate medical director meeting for formulary review. Expressed interest in speaker bureau participation pending first patient outcomes.",
  },
  {
    id: "dcr-005",
    type: "DCR",
    orgId: "ORG-45682",
    mdmId: "MDM-DCR-005",
    identifiers: ["DCR-2024-005", "VEEVA-DCR-005"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-18",
    callDate: "2024-01-18",
    hcpName: "Dr. Rebecca Williams",
    hcoName: "Children's Medical Center",
    representativeName: "Michael Thompson",
    callDuration: 35,
    callType: "Virtual",
    productsDiscussed: ["PediaCare Advanced", "GrowthSupport Pro"],
    samplesProvided: [],
    nextFollowUp: "2024-02-20",
    notes: "Initial contact with pediatric endocrinology specialist via Microsoft Teams. Dr. Williams expressed strong interest in new oral formulation suitable for pediatric patients ages 6-17. Discussed dosing considerations based on weight and BSA, safety profile in children with emphasis on growth and development monitoring. She is treating 60+ patients with growth hormone deficiency who could benefit from the improved formulation and compliance. Requested pediatric clinical trial data (PEDS-101 and PEDS-201 studies), age-appropriate dosing calculator app, and patient/parent educational videos. Discussed need for insurance coverage verification tool. Dr. Williams interested in participating in pediatric advisory board and contributing to real-world evidence study.",
  },
  {
    id: "dcr-006",
    type: "DCR",
    orgId: "ORG-45683",
    mdmId: "MDM-DCR-006",
    identifiers: ["DCR-2024-006", "SFDC-DCR-006"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-19",
    callDate: "2024-01-19",
    hcpName: "Dr. James Anderson",
    hcoName: "University Medical Research Institute",
    representativeName: "Emily Davis",
    callDuration: 75,
    callType: "In-Person",
    productsDiscussed: ["NeuroGen Plus", "CogniCare Advanced", "MindBalance"],
    samplesProvided: ["NeuroGen Plus - clinical evaluation pack"],
    nextFollowUp: "2024-02-25",
    notes: "Comprehensive meeting with neurology research team in conference room. Dr. Anderson (Principal Investigator) and 3 colleagues attended: Dr. Lisa Park (Co-PI), Dr. Thomas Rivera (Clinical Coordinator), and Dr. Amanda Zhang (Research Fellow). Discussed ongoing research collaboration opportunities and investigator-initiated trial possibilities for mild cognitive impairment population. Strong interest in NeuroGen Plus for early-stage dementia patients based on biomarker data showing 18% improvement in cognitive scores. They are conducting a 200-patient comparative effectiveness study (IRB approved, recruitment ongoing) and requested to include our product as treatment arm. Also discussed speaker bureau participation for Dr. Anderson at national conferences, research grant opportunities, and site feasibility for Phase IV post-marketing study. Provided comprehensive investigator brochure and research support contact information.",
  },
];

export const getAllEntities = () => {
  return [
    ...mockHCPs,
    ...mockHCOs,
    ...mockAddresses,
    ...mockDCRs,
  ];
};
