import { HCPProfile, HCOProfile, Address, DCRProfile } from "@/types/mdm";

export const mockHCPs: HCPProfile[] = [
  {
    id: "hcp-001",
    type: "HCP",
    orgId: "ORG-12345",
    mdmId: "MDM-PHY-001",
    identifiers: ["NPI-1234567890", "DEA-AB1234567"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-15",
    firstName: "Sarah",
    lastName: "Johnson",
    npiId: "1234567890",
    speciality: ["Cardiology", "Internal Medicine"],
    organization: "Metro Health Hospital",
    address: {
      id: "addr-001",
      type: "Address",
      orgId: "ORG-12345",
      mdmId: "MDM-ADDR-001",
      identifiers: ["ADDR-001"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "123 Medical Plaza",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-0123",
    email: "sarah.johnson@metrohealth.com",
    affiliations: ["American College of Cardiology", "AMA"],
    preferredContact: "Email",
    education: [
      {
        institution: "Harvard Medical School",
        degree: "Medical Degree",
        year: "2010",
        fieldOfStudy: "Medicine",
      },
      {
        institution: "Johns Hopkins University",
        degree: "Residency",
        year: "2014",
        fieldOfStudy: "Cardiology",
      },
    ],
    license: "MA-MD-123456",
    degreeType: "Physician",
  },
  {
    id: "hcp-002",
    type: "HCP",
    orgId: "ORG-12346",
    mdmId: "MDM-PHY-002",
    identifiers: ["NPI-9876543210"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-14",
    firstName: "Michael",
    lastName: "Chen",
    npiId: "9876543210",
    speciality: ["Oncology"],
    organization: "Cancer Treatment Center",
    address: {
      id: "addr-002",
      type: "Address",
      orgId: "ORG-12346",
      mdmId: "MDM-ADDR-002",
      identifiers: ["ADDR-002"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-0456",
    email: "m.chen@cancercenter.org",
    affiliations: ["ASCO", "AMA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "Stanford Medical School",
        degree: "Medical Degree",
        year: "2008",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "NY-MD-789012",
    degreeType: "Physician",
  },
  {
    id: "hcp-003",
    type: "HCP",
    orgId: "ORG-12347",
    mdmId: "MDM-PHY-003",
    identifiers: ["NPI-1111222233", "DEA-CD9876543"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-16",
    firstName: "Emily",
    lastName: "Rodriguez",
    npiId: "1111222233",
    speciality: ["Pediatrics", "Neonatology"],
    organization: "Children's Medical Center",
    address: {
      id: "addr-009",
      type: "Address",
      orgId: "ORG-12347",
      mdmId: "MDM-ADDR-009",
      identifiers: ["ADDR-009"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-12",
      street: "200 Pediatric Circle",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-213-555-7890",
    email: "e.rodriguez@childrensmedical.org",
    affiliations: ["AAP", "American Board of Pediatrics"],
    preferredContact: "Email",
    education: [
      {
        institution: "UCLA Medical School",
        degree: "Medical Degree",
        year: "2012",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "CA-MD-456789",
    degreeType: "Physician",
  },
  {
    id: "hcp-004",
    type: "HCP",
    orgId: "ORG-12348",
    mdmId: "MDM-PHY-004",
    identifiers: ["NPI-4444555566"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-13",
    firstName: "David",
    lastName: "Patel",
    npiId: "4444555566",
    speciality: ["Neurology", "Stroke Medicine"],
    organization: "University Medical Research Institute",
    address: {
      id: "addr-010",
      type: "Address",
      orgId: "ORG-12348",
      mdmId: "MDM-ADDR-010",
      identifiers: ["ADDR-010"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-11",
      street: "500 University Circle",
      city: "Chicago",
      state: "IL",
      zipCode: "60637",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-312-555-6789",
    email: "d.patel@umri.edu",
    affiliations: ["AAN", "American Stroke Association"],
    preferredContact: "Phone",
    education: [
      {
        institution: "Northwestern University",
        degree: "Medical Degree",
        year: "2009",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "IL-MD-234567",
    degreeType: "Physician",
  },
  {
    id: "hcp-005",
    type: "HCP",
    orgId: "ORG-12349",
    mdmId: "MDM-PHY-005",
    identifiers: ["NPI-7777888899", "DEA-EF1234567"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-17",
    firstName: "Jennifer",
    lastName: "Martinez",
    npiId: "7777888899",
    speciality: ["Orthopedic Surgery", "Sports Medicine"],
    organization: "Metro Health Hospital",
    address: {
      id: "addr-011",
      type: "Address",
      orgId: "ORG-12349",
      mdmId: "MDM-ADDR-011",
      identifiers: ["ADDR-011"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "789 Healthcare Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-3456",
    email: "j.martinez@metrohealth.com",
    affiliations: ["AAOS", "American Orthopedic Society for Sports Medicine"],
    preferredContact: "Email",
    education: [
      {
        institution: "Boston University Medical School",
        degree: "Medical Degree",
        year: "2011",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "MA-MD-567890",
    degreeType: "Physician",
  },
  {
    id: "hcp-006",
    type: "HCP",
    orgId: "ORG-12350",
    mdmId: "MDM-PHY-006",
    identifiers: ["NPI-3333444455"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-18",
    firstName: "Robert",
    lastName: "Thompson",
    npiId: "3333444455",
    speciality: ["Gastroenterology"],
    organization: "City General Hospital",
    address: {
      id: "addr-012",
      type: "Address",
      orgId: "ORG-12350",
      mdmId: "MDM-ADDR-012",
      identifiers: ["ADDR-012"],
      status: "Pending",
      source: "Manual Entry",
      lastUpdated: "2024-01-18",
      street: "150 Main Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      country: "USA",
      addressType: "Primary",
      verified: false,
    },
    phone: "+1-206-555-1234",
    email: "r.thompson@citygeneral.org",
    affiliations: ["AGA"],
    preferredContact: "Email",
    education: [
      {
        institution: "University of Washington",
        degree: "Medical Degree",
        year: "2013",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "WA-MD-678901",
    degreeType: "Physician",
  },
  {
    id: "hcp-007",
    type: "HCP",
    orgId: "ORG-12351",
    mdmId: "MDM-PHY-007",
    identifiers: ["NPI-6666777788", "DEA-GH5678901"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-12",
    firstName: "Lisa",
    lastName: "Anderson",
    npiId: "6666777788",
    speciality: ["Dermatology"],
    organization: "Skin Care Specialists",
    address: {
      id: "addr-013",
      type: "Address",
      orgId: "ORG-12351",
      mdmId: "MDM-ADDR-013",
      identifiers: ["ADDR-013"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "400 Dermatology Lane",
      city: "Miami",
      state: "FL",
      zipCode: "33101",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-305-555-2345",
    email: "l.anderson@skincare.com",
    affiliations: ["AAD", "American Society for Dermatologic Surgery"],
    preferredContact: "Phone",
    education: [
      {
        institution: "University of Miami",
        degree: "Medical Degree",
        year: "2010",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "FL-MD-789012",
    degreeType: "Physician",
  },
  {
    id: "hcp-008",
    type: "HCP",
    orgId: "ORG-12352",
    mdmId: "MDM-PHY-008",
    identifiers: ["NPI-9999000011"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-19",
    firstName: "William",
    lastName: "Davis",
    npiId: "9999000011",
    speciality: ["Psychiatry", "Child Psychiatry"],
    organization: "Mental Health Institute",
    address: {
      id: "addr-014",
      type: "Address",
      orgId: "ORG-12352",
      mdmId: "MDM-ADDR-014",
      identifiers: ["ADDR-014"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-17",
      street: "600 Wellness Drive",
      city: "Denver",
      state: "CO",
      zipCode: "80202",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-303-555-4567",
    email: "w.davis@mentalhealth.org",
    affiliations: ["APA", "AACAP"],
    preferredContact: "Email",
    education: [
      {
        institution: "University of Colorado",
        degree: "Medical Degree",
        year: "2014",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "CO-MD-890123",
    degreeType: "Physician",
  },
  {
    id: "hcp-009",
    type: "HCP",
    orgId: "ORG-12353",
    mdmId: "MDM-PHY-009",
    identifiers: ["NPI-2222333344", "DEA-IJ7890123"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-11",
    firstName: "Amanda",
    lastName: "Wilson",
    npiId: "2222333344",
    speciality: ["Emergency Medicine"],
    organization: "City General Hospital",
    address: {
      id: "addr-015",
      type: "Address",
      orgId: "ORG-12353",
      mdmId: "MDM-ADDR-015",
      identifiers: ["ADDR-015"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-09",
      street: "150 Main Street",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-206-555-5678",
    email: "a.wilson@citygeneral.org",
    affiliations: ["ACEP", "AMA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "University of Washington",
        degree: "Medical Degree",
        year: "2012",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "WA-MD-901234",
    degreeType: "Physician",
  },
  {
    id: "hcp-010",
    type: "HCP",
    orgId: "ORG-12354",
    mdmId: "MDM-PHY-010",
    identifiers: ["NPI-5555666677"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-20",
    firstName: "Daniel",
    lastName: "Lee",
    npiId: "5555666677",
    speciality: ["Radiology", "Nuclear Medicine"],
    organization: "Imaging Center of Excellence",
    address: {
      id: "addr-016",
      type: "Address",
      orgId: "ORG-12354",
      mdmId: "MDM-ADDR-016",
      identifiers: ["ADDR-016"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-18",
      street: "700 Imaging Boulevard",
      city: "Houston",
      state: "TX",
      zipCode: "77002",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-713-555-6789",
    email: "d.lee@imagingcenter.com",
    affiliations: ["ACR", "RSNA"],
    preferredContact: "Email",
    education: [
      {
        institution: "Baylor College of Medicine",
        degree: "Medical Degree",
        year: "2011",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "TX-MD-012345",
    degreeType: "Physician",
  },
  {
    id: "hcp-011",
    type: "HCP",
    orgId: "ORG-12355",
    mdmId: "MDM-PHY-011",
    identifiers: ["NPI-8888999900", "DEA-KL1234567"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-10",
    firstName: "Patricia",
    lastName: "Garcia",
    npiId: "8888999900",
    speciality: ["Obstetrics", "Gynecology"],
    organization: "Women's Health Clinic",
    address: {
      id: "addr-017",
      type: "Address",
      orgId: "ORG-12355",
      mdmId: "MDM-ADDR-017",
      identifiers: ["ADDR-017"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-08",
      street: "800 Women's Way",
      city: "Phoenix",
      state: "AZ",
      zipCode: "85001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-602-555-7890",
    email: "p.garcia@womenshealth.org",
    affiliations: ["ACOG", "AMA"],
    preferredContact: "Email",
    education: [
      {
        institution: "University of Arizona",
        degree: "Medical Degree",
        year: "2013",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "AZ-MD-123456",
    degreeType: "Physician",
  },
  {
    id: "hcp-012",
    type: "HCP",
    orgId: "ORG-12356",
    mdmId: "MDM-PHY-012",
    identifiers: ["NPI-1112223334"],
    status: "Inactive",
    source: "Manual Entry",
    lastUpdated: "2024-01-09",
    firstName: "Christopher",
    lastName: "Brown",
    npiId: "1112223334",
    speciality: ["Anesthesiology"],
    organization: "Surgical Associates",
    address: {
      id: "addr-018",
      type: "Address",
      orgId: "ORG-12356",
      mdmId: "MDM-ADDR-018",
      identifiers: ["ADDR-018"],
      status: "Inactive",
      source: "Manual Entry",
      lastUpdated: "2024-01-09",
      street: "900 Surgery Center",
      city: "Atlanta",
      state: "GA",
      zipCode: "30301",
      country: "USA",
      addressType: "Primary",
      verified: false,
    },
    phone: "+1-404-555-8901",
    email: "c.brown@surgicalassoc.com",
    affiliations: ["ASA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "Emory University",
        degree: "Medical Degree",
        year: "2009",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "GA-MD-234567",
    degreeType: "Physician",
  },
  {
    id: "hcp-013",
    type: "HCP",
    orgId: "ORG-12357",
    mdmId: "MDM-PHY-013",
    identifiers: ["NPI-4445556667", "DEA-MN9876543"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-21",
    firstName: "Susan",
    lastName: "White",
    npiId: "4445556667",
    speciality: ["Endocrinology", "Diabetes"],
    organization: "Diabetes Care Center",
    address: {
      id: "addr-019",
      type: "Address",
      orgId: "ORG-12357",
      mdmId: "MDM-ADDR-019",
      identifiers: ["ADDR-019"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-19",
      street: "250 Endocrine Avenue",
      city: "Philadelphia",
      state: "PA",
      zipCode: "19101",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-215-555-9012",
    email: "s.white@diabetescare.org",
    affiliations: ["AACE", "Endocrine Society"],
    preferredContact: "Email",
    education: [
      {
        institution: "University of Pennsylvania",
        degree: "Medical Degree",
        year: "2012",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "PA-MD-345678",
    degreeType: "Physician",
  },
  {
    id: "hcp-014",
    type: "HCP",
    orgId: "ORG-12358",
    mdmId: "MDM-PHY-014",
    identifiers: ["NPI-7778889990"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-22",
    firstName: "Kevin",
    lastName: "Harris",
    npiId: "7778889990",
    speciality: ["Urology"],
    organization: "Urology Specialists Group",
    address: {
      id: "addr-020",
      type: "Address",
      orgId: "ORG-12358",
      mdmId: "MDM-ADDR-020",
      identifiers: ["ADDR-020"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-20",
      street: "350 Urology Plaza",
      city: "San Diego",
      state: "CA",
      zipCode: "92101",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-619-555-0123",
    email: "k.harris@urologyspecialists.com",
    affiliations: ["AUA"],
    preferredContact: "Phone",
    education: [
      {
        institution: "UC San Diego",
        degree: "Medical Degree",
        year: "2010",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "CA-MD-456789",
    degreeType: "Physician",
  },
  {
    id: "hcp-015",
    type: "HCP",
    orgId: "ORG-12359",
    mdmId: "MDM-PHY-015",
    identifiers: ["NPI-2223334445", "DEA-OP5432109"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-23",
    firstName: "Michelle",
    lastName: "Taylor",
    npiId: "2223334445",
    speciality: ["Rheumatology"],
    organization: "Arthritis Treatment Center",
    address: {
      id: "addr-021",
      type: "Address",
      orgId: "ORG-12359",
      mdmId: "MDM-ADDR-021",
      identifiers: ["ADDR-021"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-21",
      street: "450 Rheumatology Road",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-503-555-1234",
    email: "m.taylor@arthritistreatment.org",
    affiliations: ["ACR", "AMA"],
    preferredContact: "Email",
    education: [
      {
        institution: "Oregon Health & Science University",
        degree: "Medical Degree",
        year: "2014",
        fieldOfStudy: "Medicine",
      },
    ],
    license: "OR-MD-567890",
    degreeType: "Physician",
  },
];

export const mockHCOs: HCOProfile[] = [
  {
    id: "hco-001",
    type: "HCO",
    orgId: "ORG-23456",
    mdmId: "MDM-FAC-001",
    identifiers: ["NPI-1122334455", "TIN-12-3456789", "CLIA-12D0123456"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-12",
    name: "Metro Health Hospital",
    npiId: "1122334455",
    organizationType: "General Hospital",
    address: {
      id: "addr-003",
      type: "Address",
      orgId: "ORG-23456",
      mdmId: "MDM-ADDR-003",
      identifiers: ["ADDR-003"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "789 Healthcare Blvd",
      city: "Boston",
      state: "MA",
      zipCode: "02115",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-617-555-1000",
    email: "info@metrohealth.com",
    affiliatedHCPs: ["hcp-001", "hcp-003", "hcp-004"],
    departments: ["Cardiology", "Oncology", "Emergency Medicine", "Surgery", "Pediatrics", "Radiology"],
    accreditation: ["Joint Commission - Gold Seal", "DNV GL Healthcare", "Magnet Recognition Program"],
  },
  {
    id: "hco-002",
    type: "HCO",
    orgId: "ORG-23457",
    mdmId: "MDM-FAC-002",
    identifiers: ["NPI-5566778899", "TIN-45-9876543"],
    status: "Active",
    source: "CMS",
    lastUpdated: "2024-01-11",
    name: "Cancer Treatment Center",
    npiId: "5566778899",
    organizationType: "Specialty Hospital",
    address: {
      id: "addr-004",
      type: "Address",
      orgId: "ORG-23457",
      mdmId: "MDM-ADDR-004",
      identifiers: ["ADDR-004"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-10",
      street: "456 Oncology Drive",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-212-555-2000",
    email: "contact@cancercenter.org",
    affiliatedHCPs: ["hcp-002"],
    departments: ["Medical Oncology", "Radiation Oncology", "Surgical Oncology", "Hematology", "Palliative Care"],
    accreditation: ["ASCO QOPI Certification", "Joint Commission", "Commission on Cancer Accreditation"],
  },
  {
    id: "hco-003",
    type: "HCO",
    orgId: "ORG-23458",
    mdmId: "MDM-FAC-003",
    identifiers: ["NPI-7788990011", "TIN-98-7654321", "CLIA-05D0987654"],
    status: "Active",
    source: "Epic EMR",
    lastUpdated: "2024-01-16",
    name: "Children's Medical Center",
    npiId: "7788990011",
    organizationType: "Pediatric Hospital",
    address: {
      id: "addr-007",
      type: "Address",
      orgId: "ORG-23458",
      mdmId: "MDM-ADDR-007",
      identifiers: ["ADDR-007"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "100 Children's Way",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90012",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-213-555-3000",
    email: "info@childrensmedical.org",
    affiliatedHCPs: ["hcp-005", "hcp-006", "hcp-007"],
    departments: ["Pediatric Surgery", "Neonatal ICU", "Pediatric Cardiology", "Pediatric Oncology", "Emergency Pediatrics", "Pediatric Neurology"],
    accreditation: ["Magnet Recognition Program", "Joint Commission - Gold Seal", "Children's Hospital Association Member", "Beacon Award Excellence"],
  },
  {
    id: "hco-004",
    type: "HCO",
    orgId: "ORG-23459",
    mdmId: "MDM-FAC-004",
    identifiers: ["NPI-2233445566", "TIN-36-5432198", "CLIA-14D1122334"],
    status: "Active",
    source: "Cerner",
    lastUpdated: "2024-01-17",
    name: "University Medical Research Institute",
    npiId: "2233445566",
    organizationType: "Academic Medical Center",
    address: {
      id: "addr-008",
      type: "Address",
      orgId: "ORG-23459",
      mdmId: "MDM-ADDR-008",
      identifiers: ["ADDR-008"],
      status: "Active",
      source: "USPS",
      lastUpdated: "2024-01-15",
      street: "500 University Circle",
      city: "Chicago",
      state: "IL",
      zipCode: "60637",
      country: "USA",
      addressType: "Primary",
      verified: true,
    },
    phone: "+1-312-555-4000",
    email: "research@umri.edu",
    affiliatedHCPs: ["hcp-001", "hcp-002", "hcp-008", "hcp-009"],
    departments: ["Clinical Research", "Neurology", "Psychiatry", "Internal Medicine", "Infectious Diseases", "Genomics", "Immunology"],
    accreditation: ["AAHRPP Accreditation", "CAP Laboratory Accreditation", "Joint Commission", "NCQA Patient-Centered Specialty Practice"],
  },
];

export const mockAddresses: Address[] = [
  {
    id: "addr-005",
    type: "Address",
    orgId: "ORG-34567",
    mdmId: "MDM-ADDR-005",
    identifiers: ["ADDR-005"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-13",
    street: "321 Research Parkway",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-006",
    type: "Address",
    orgId: "ORG-34568",
    mdmId: "MDM-ADDR-006",
    identifiers: ["ADDR-006"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-14",
    street: "555 Medical Center Way",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
  {
    id: "addr-022",
    type: "Address",
    orgId: "ORG-34569",
    mdmId: "MDM-ADDR-022",
    identifiers: ["ADDR-022"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-15",
    street: "100 Innovation Drive",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-023",
    type: "Address",
    orgId: "ORG-34570",
    mdmId: "MDM-ADDR-023",
    identifiers: ["ADDR-023"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-16",
    street: "75 Technology Boulevard",
    city: "San Jose",
    state: "CA",
    zipCode: "95101",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-024",
    type: "Address",
    orgId: "ORG-34571",
    mdmId: "MDM-ADDR-024",
    identifiers: ["ADDR-024"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-17",
    street: "250 Commerce Street",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
  {
    id: "addr-025",
    type: "Address",
    orgId: "ORG-34572",
    mdmId: "MDM-ADDR-025",
    identifiers: ["ADDR-025"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-18",
    street: "500 Financial Plaza",
    city: "Charlotte",
    state: "NC",
    zipCode: "28201",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-026",
    type: "Address",
    orgId: "ORG-34573",
    mdmId: "MDM-ADDR-026",
    identifiers: ["ADDR-026"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-19",
    street: "825 Enterprise Way",
    city: "Nashville",
    state: "TN",
    zipCode: "37201",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-027",
    type: "Address",
    orgId: "ORG-34574",
    mdmId: "MDM-ADDR-027",
    identifiers: ["ADDR-027"],
    status: "Active",
    source: "Google Maps",
    lastUpdated: "2024-01-20",
    street: "1200 Market Street",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19101",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-028",
    type: "Address",
    orgId: "ORG-34575",
    mdmId: "MDM-ADDR-028",
    identifiers: ["ADDR-028"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-21",
    street: "600 Corporate Center",
    city: "Columbus",
    state: "OH",
    zipCode: "43201",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
  {
    id: "addr-029",
    type: "Address",
    orgId: "ORG-34576",
    mdmId: "MDM-ADDR-029",
    identifiers: ["ADDR-029"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-22",
    street: "950 Business Park Drive",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46201",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-030",
    type: "Address",
    orgId: "ORG-34577",
    mdmId: "MDM-ADDR-030",
    identifiers: ["ADDR-030"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-23",
    street: "1500 Lakefront Avenue",
    city: "Milwaukee",
    state: "WI",
    zipCode: "53201",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
  {
    id: "addr-031",
    type: "Address",
    orgId: "ORG-34578",
    mdmId: "MDM-ADDR-031",
    identifiers: ["ADDR-031"],
    status: "Active",
    source: "Google Maps",
    lastUpdated: "2024-01-24",
    street: "2000 Summit Boulevard",
    city: "Kansas City",
    state: "MO",
    zipCode: "64101",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-032",
    type: "Address",
    orgId: "ORG-34579",
    mdmId: "MDM-ADDR-032",
    identifiers: ["ADDR-032"],
    status: "Pending",
    source: "Manual Entry",
    lastUpdated: "2024-01-25",
    street: "300 Riverfront Plaza",
    city: "Louisville",
    state: "KY",
    zipCode: "40201",
    country: "USA",
    addressType: "Billing",
    verified: false,
  },
  {
    id: "addr-033",
    type: "Address",
    orgId: "ORG-34580",
    mdmId: "MDM-ADDR-033",
    identifiers: ["ADDR-033"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-26",
    street: "700 Harbor Drive",
    city: "Baltimore",
    state: "MD",
    zipCode: "21201",
    country: "USA",
    addressType: "Primary",
    verified: true,
  },
  {
    id: "addr-034",
    type: "Address",
    orgId: "ORG-34581",
    mdmId: "MDM-ADDR-034",
    identifiers: ["ADDR-034"],
    status: "Active",
    source: "USPS",
    lastUpdated: "2024-01-27",
    street: "1800 Convention Center",
    city: "Las Vegas",
    state: "NV",
    zipCode: "89101",
    country: "USA",
    addressType: "Secondary",
    verified: true,
  },
];

export const mockDCRs: DCRProfile[] = [
  {
    id: "dcr-001",
    type: "DCR",
    orgId: "ORG-45678",
    mdmId: "MDM-DCR-001",
    identifiers: ["DCR-2024-001", "VEEVA-DCR-001"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-15",
    callDate: "2024-01-15",
    hcpName: "Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 45,
    callType: "In-Person",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus"],
    samplesProvided: ["CardioMed Pro - 30 samples"],
    nextFollowUp: "2024-02-15",
    notes: "Discussed latest clinical trial results showing 23% reduction in cardiovascular events. Johnson expressed strong interest in CardioMed Pro for high-risk patients with diabetes and hypertension comorbidities. She mentioned that 15-20% of her patient base (approximately 200 patients) could benefit from this treatment. Requested peer-reviewed studies from NEJM and JAMA, patient case studies for review, and formulary addition process information. Discussed reimbursement pathways and patient assistance programs. Johnson agreed to pilot program with 10 selected patients.",
  },
  {
    id: "dcr-002",
    type: "DCR",
    orgId: "ORG-45679",
    mdmId: "MDM-DCR-002",
    identifiers: ["DCR-2024-002", "VEEVA-DCR-002"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-14",
    callDate: "2024-01-14",
    hcpName: "Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Emily Davis",
    callDuration: 30,
    callType: "Virtual",
    productsDiscussed: ["OncoTherapy X", "ImmuneBoost"],
    samplesProvided: [],
    nextFollowUp: "2024-02-01",
    notes: "Virtual meeting via Zoom to discuss OncoTherapy X Phase III efficacy data showing 35% improvement in progression-free survival. Chen requested additional research materials including mechanism of action videos, access to the latest clinical trial publications from Lancet Oncology, and detailed adverse event profiles. He is currently treating 40+ patients with metastatic disease who could potentially benefit. Discussed combination therapy protocols with existing treatments and patient monitoring requirements. Scheduled follow-up for detailed adverse event management training.",
  },
  {
    id: "dcr-003",
    type: "DCR",
    orgId: "ORG-45680",
    mdmId: "MDM-DCR-003",
    identifiers: ["DCR-2024-003", "VEEVA-DCR-003"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-16",
    callDate: "2024-01-16",
    hcpName: "Sarah Johnson",
    hcoName: "Metro Health Hospital",
    representativeName: "John Smith",
    callDuration: 60,
    callType: "Group Presentation",
    productsDiscussed: ["CardioMed Pro", "HeartGuard Plus", "VascularCare Elite"],
    samplesProvided: ["HeartGuard Plus - 50 samples", "VascularCare Elite - 25 samples"],
    nextFollowUp: "2024-03-01",
    notes: "Group presentation to cardiology department grand rounds. 8 physicians attended including Johnson (Department Head), Martinez (Interventional Cardiology), Patel (Heart Failure), and 5 attending cardiologists. Presented updated safety profile with 2-year real-world evidence data from 15,000+ patients and comparative effectiveness analysis vs. standard of care. Department head Johnson very receptive and supportive. Several physicians requested P&T committee formulary addition consideration for March meeting. Strong interest in combination therapy protocols for complex patients. Discussed department-wide educational program and continuing medical education opportunities. Follow-up scheduled for detailed P&T submission support.",
  },
  {
    id: "dcr-004",
    type: "DCR",
    orgId: "ORG-45681",
    mdmId: "MDM-DCR-004",
    identifiers: ["DCR-2024-004", "SFDC-DCR-004"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-17",
    callDate: "2024-01-17",
    hcpName: "Michael Chen",
    hcoName: "Cancer Treatment Center",
    representativeName: "Sarah Martinez",
    callDuration: 40,
    callType: "In-Person",
    productsDiscussed: ["OncoTherapy X", "NeoGenesis"],
    samplesProvided: ["OncoTherapy X - starter pack"],
    nextFollowUp: "2024-02-10",
    notes: "Follow-up on previous virtual call. Chen reviewed clinical data packages and is ready to initiate first 5 patients on OncoTherapy X within 2 weeks. Discussed detailed patient selection criteria: Stage III/IV disease, ECOG 0-1, adequate organ function. Reviewed monitoring protocols including baseline and week 4, 8, 12 assessments. Provided patient education materials in English and Spanish. Discussed financial assistance - requested support for patient financial assistance program enrollment and prior authorization process. Chen committed to presenting at upcoming tumor board and will facilitate medical director meeting for formulary review. Expressed interest in speaker bureau participation pending first patient outcomes.",
  },
  {
    id: "dcr-005",
    type: "DCR",
    orgId: "ORG-45682",
    mdmId: "MDM-DCR-005",
    identifiers: ["DCR-2024-005", "VEEVA-DCR-005"],
    status: "Active",
    source: "Veeva CRM",
    lastUpdated: "2024-01-18",
    callDate: "2024-01-18",
    hcpName: "Rebecca Williams",
    hcoName: "Children's Medical Center",
    representativeName: "Michael Thompson",
    callDuration: 35,
    callType: "Virtual",
    productsDiscussed: ["PediaCare Advanced", "GrowthSupport Pro"],
    samplesProvided: [],
    nextFollowUp: "2024-02-20",
    notes: "Initial contact with pediatric endocrinology specialist via Microsoft Teams. Williams expressed strong interest in new oral formulation suitable for pediatric patients ages 6-17. Discussed dosing considerations based on weight and BSA, safety profile in children with emphasis on growth and development monitoring. She is treating 60+ patients with growth hormone deficiency who could benefit from the improved formulation and compliance. Requested pediatric clinical trial data (PEDS-101 and PEDS-201 studies), age-appropriate dosing calculator app, and patient/parent educational videos. Discussed need for insurance coverage verification tool. Williams interested in participating in pediatric advisory board and contributing to real-world evidence study.",
  },
  {
    id: "dcr-006",
    type: "DCR",
    orgId: "ORG-45683",
    mdmId: "MDM-DCR-006",
    identifiers: ["DCR-2024-006", "SFDC-DCR-006"],
    status: "Active",
    source: "Salesforce Health Cloud",
    lastUpdated: "2024-01-19",
    callDate: "2024-01-19",
    hcpName: "James Anderson",
    hcoName: "University Medical Research Institute",
    representativeName: "Emily Davis",
    callDuration: 75,
    callType: "In-Person",
    productsDiscussed: ["NeuroGen Plus", "CogniCare Advanced", "MindBalance"],
    samplesProvided: ["NeuroGen Plus - clinical evaluation pack"],
    nextFollowUp: "2024-02-25",
    notes: "Comprehensive meeting with neurology research team in conference room. Anderson (Principal Investigator) and 3 colleagues attended: Lisa Park (Co-PI), Thomas Rivera (Clinical Coordinator), and Amanda Zhang (Research Fellow). Discussed ongoing research collaboration opportunities and investigator-initiated trial possibilities for mild cognitive impairment population. Strong interest in NeuroGen Plus for early-stage dementia patients based on biomarker data showing 18% improvement in cognitive scores. They are conducting a 200-patient comparative effectiveness study (IRB approved, recruitment ongoing) and requested to include our product as treatment arm. Also discussed speaker bureau participation for Anderson at national conferences, research grant opportunities, and site feasibility for Phase IV post-marketing study. Provided comprehensive investigator brochure and research support contact information.",
  },
];

export const getAllEntities = () => {
  return [
    ...mockHCPs,
    ...mockHCOs,
    ...mockAddresses,
    ...mockDCRs,
  ];
};
